name: note_timer
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1

  # Router
  go_router: ^14.6.2

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.3.2

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # SVG
  flutter_svg: ^2.0.10

  # Responsive UI
  flutter_screenutil: ^5.9.0

  # Supabase
  supabase_flutter: ^2.9.0
  google_sign_in: ^6.2.2

  # Environment Variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash/
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: NanumGothic
      fonts:
        - asset: assets/fonts/NanumGothic-Regular.ttf
        - asset: assets/fonts/NanumGothic-Bold.ttf
          weight: 700